### ISSUE TITLE
Error using rectangle in calibration.

### ISSUE THREAD

**Issue by shshnkydv** [jacopoantonello/mshwfs#1]
I am using .bmp image for calibration after converting it into .mat. When I reduce the shstruct.coarse_grid_radius, i.e.radius for coarse grid from 16 to 10, for instance, the error that comes is, "any non finite? 1". It happens with some images. Most of the images can manage coarse grid radius of a wide range like (10,16). Some can take only above 15. I guess, one of the centers in shwfs_make_fine_grid code takes non-finite value, which one, I don't know. What to do to handle this error?

**Comment by jacopoantonello** [comment]
All elements of `centres` must be finite, otherwise some slopes will also be non-finite. Can you post your mat file and the value of `shstruct.coarse_grid_radius` for which you get this error?

**Comment by shshnkydv** [comment]
The image I was using has a white border. So the program was also creating the border's centroid, considering it a giant connected white spot. So for 120 lenses I was getting 121 spots. The threshold for removing spots less than a certain size was 8. I added an upper limit on the size of objects also, as 80 pixels. After that I got 120 objects and the error was rectified. Earlier I was getting the error for every value of shstruct.coarse_grid_radius less than 14. I will mail you the mat file. Thanks for the reply.
Here are the screen shots of the changed code and the calibration image.

![capture3](https://cloud.githubusercontent.com/assets/19145472/15005913/1f405820-11e8-11e6-9f0f-b296c7787202.JPG)
![capture1](https://cloud.githubusercontent.com/assets/19145472/15005914/1f428bea-11e8-11e6-8db1-cf03c9a86190.JPG)

**Comment by shshnkydv** [comment]
I have attached the mat file. The calibration was giving error if the value
for shstruct.coarse_grid_radius was less than 14. And 15 for some other
images.

**Comment by jacopoantonello** [comment]
I'm afraid I can't find any attached mat file. In any case this seems to me a non-issue. Clearly you cannot use an image with a white border. The code tries to identify spots by looking at the white level. You should crop your image first. Also you should be using raw images from a CCD. If not your images may be resampled and you won't know for sure what units you are measuring, like rads or um.

**Comment by shshnkydv** [comment]
I tried to attach the mat file here but couldn't so I mailed it through my gmail account. It seems it didn't reach. Can you provide me a mail account for it?
It's clearly is a non-issue. I am using only raw images from CCD. Only alteration is cropping to get 120 spots.

**Comment by jacopoantonello** [comment]
My email address is found in the m files and in the license file. Send me the bmp, I will have a look this weekend.

**Comment by jacopoantonello** [comment]
Closing this issue. As far as I can tell this was not an issue at all, as only raw Shack Hartmann images should be used. The white border is probably due to using `saveas` instead of `imwrite` when saving the raw data with MATLAB.
