### ISSUE TITLE
The relationship between the reconstructed wavefront and the actual wavefront.

### ISSUE THREAD

**Issue by Donghuajie** [jacopoantonello/mshwfs#2]
Hi author, I would like to ask, the range of the wavefront reconstructed from this project is only the size of the unit circle, but the size of the whole pupil is not necessarily the unit circle. So I would like to ask how to map the reconstructed wavefront to the actual measured wavefront?

**Comment by jacopoantonello** [comment]
Hi. Zernike polynomials work on circular pupils. I'm afraid this code doesn't support other pupil shapes.
